MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.15                      # [osx and x86_64]
channel_sources:
  - conda-forge
channel_targets:
  - tiledb main
libdeflate:  # [linux]
  - 1.17     # [linux]
  - 1.25     # [linux]
